accessing
thrownExceptions: anObject
	thrownExceptions value: anObject