accessing
expectedError: anObject
	expectedError := anObject