accessing
declaredExceptions: anObject
	declaredExceptions value: anObject